version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: attendance-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - qrnet

  backend:
    build:
      context: .
      dockerfile: AttendanceQR.Server/Dockerfile
    container_name: attendance-backend
    ports:
      - "5008:8080"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=attendance;Username=postgres;Password=postgres"
    depends_on:
      - postgres
    networks:
      - qrnet

  frontend:
    build:
      context: attendanceqr.client
      dockerfile: Dockerfile
    container_name: attendance-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - qrnet

volumes:
  pgdata:

networks:
  qrnet:
